dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3399-eaio-3399j.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3399-bozz-sw799a-5g.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3399-cdhx-rb30.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3399-fine3399.dtb